### ISSUE TITLE
Exception in message_received_rt when handling msg on

### ISSUE THREAD

**Issue by clpodes** [orbis-developers/home_assistant_viaris#9] opened 2024-10-15 14:47 UTC
[home-assistant_viaris_2024-10-15T14-41-42.644Z.log](https://github.com/user-attachments/files/17380419/home-assistant_viaris_2024-10-15T14-41-42.644Z.log)
Good evening,
I installed your integration, but it keeps reporting these errors (it makes a lot of them)
Thank you
Claudio

**Comment by HGC72** [comment] 2024-10-17 09:24
Hello, 
Thank you for your message. The reason for the issue is that your equipment is configured as SPL, and in this configuration, certain fields are not present in the RT frame. Version 0.2.0 has been generated, and you will see that the error messages no longer appear.

Regards,

**Comment by clpodes** [comment] 2024-10-18 08:19
Thank you very much!

**Comment by HGC72** [comment] 2024-10-21 05:12
You are welcome. I am closing this issue as it appears to be resolved.
Regards.

**Closed as completed** 2024-10-21 05:12 UTC
